### ISSUE TITLE
Great Idea! Looks awfully familiar...

### ISSUE THREAD

**Issue by tuckershannon** [drspangle/plot-clock#3]
Any reason you removed all reference to myself or the original plotclock designer Johannes Heberlein? 

https://www.thingiverse.com/thing:2833916

**Comment by drspangle** [comment]
This wasn't supposed to be public yet. I was cleaning up the code and
recreating all the .sldprt files before I made a release (which would
obviously credit everyone). How'd you end up finding this, anyway?

**Comment by drspangle** [comment]
I removed the random MIT license I originally had in here and added the correct CC license. I also put the appropriate attribution text into the source code (as well as the `LICENSE` file, which ought to have been in here).

Fixed in bf4489e.
